---
AWSTemplateFormatVersion: "2010-09-09"

Description: creates an Account Vending Machine as a CustomResource

Parameters:
  pAccount:
    Description: the account name that will own the resource
    Type: String
    
  pDomain:
    Description: the domain name that owns the account
    Type: String
    
  pEnvironment:
    AllowedValues:
      - prd
    Description: the environment name that the resources are deployed into
    Type: String
    
  pOwner:
    Description: the email of the user that will own the resources
    Type: String
    
Resources:
  rProduct:
    Type: Custom::AccountVendingMachine
    Properties:
      ServiceToken: <Lambda ARN>