---
AWSTemplateFormatVersion: "2010-09-09"

Description: creates an Account Vending Machine as a CustomResource

Parameters:
  pAccount:
    Description: the account name that will own the resource
    Type: String
    
  pDomain:
    Description: the domain name that owns the account
    Type: String
    
  pEnvironment:
    AllowedValues:
      - prd
    Description: the environment name that the resources are deployed into
    Type: String
    
  pOwner:
    Description: the email of the user that will own the resources
    Type: String
    
  pOuName:
    Description: the ou name to move the newly created account to
    Type: String
    
Resources:
  rAccountVendingMachine:
    Type: Custom::AccountVendingMachine
    Properties:
      ServiceToken: a
      AccountName: !Ref pAccount
      Domain: !Ref pDomain
      Environment: !Ref pEnvironment
      OuRootId: r-fgwv
      OuName: !Ref pOuName
      Owner: !Ref pOwner
      